### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by girardinsamuel** [zodman/inertia-django#19]
Hi ! 

Would it possible to make a new release of the latest changes on PyPi ? The latest is 0.3.2 and is from 27 october 2020..

Thank you in advance !

**Comment by girardinsamuel** [comment]
@zodman hello !

Would it possible to make a new release of the latest changes on PyPi ?

**Comment by muarachmann** [comment]
@zodman 👍🏽  can you please

**Comment by girardinsamuel** [comment]
I refactored this package as an other package https://github.com/girardinsamuel/django-inertia/. I made a first release, I still need to add documentation and type hinting in the code. But it's ready ! I will maintain this new one as this one seems to be less maintained.

Hoping it's okay for you @zodman ?

I am also maintaining https://github.com/girardinsamuel/masonite-inertia/ for the incredible [MasoniteFramework](https://docs.masoniteproject.com/).
