### ISSUE TITLE
CSRFToken

### ISSUE THREAD

**Issue by kasparpollet** [zodman/inertia-django#21]
Hi,

I have some troubles using forms in react.The problem is that I am not able to make a post request using the right CSRFToken. I know that I am using the right CSRF token that Django gives me inside the form. When I try to use the Inertia.post from https://inertiajs.com/forms i get the 403: "CSRF verification failed. Request aborted.". When I use my own action url in the from tag the CSRFToken does work but I don't have my form data. 

```
function EmailFrom() {
    const [values, setValues] = useState({
        email: '',
    })

    function handleChange(e) {
        const key = e.target.id;
        const value = e.target.value
        setValues(values => ({
            ...values,
            [key]: value,
        }))
    }

    const token = document.getElementsByName("csrfmiddlewaretoken")[0].value 
    return (
        <div>
            <form action="/submit_email/" method="POST">
                <input type="hidden" name="csrfmiddlewaretoken" value={token}></input>          
                <label htmlFor="email">Email: </label>
                <input id="email" value={values.email} onChange={handleChange} />
                <button type="submit">Submit</button>
            </form>            
        </div>
    )
}

```
Or with the Inertia.post

```
function submit(e) {
    e.preventDefault()
    Inertia.post('/submit_email/')
}

const token = document.getElementsByName("csrfmiddlewaretoken")[0].value 
return (
    <div>
        <form onSubmit={submit}>
            <input type="hidden" name="csrfmiddlewaretoken" value={token}></input>          
            <label htmlFor="email">Email: </label>
            <input id="email" value={values.email} onChange={handleChange} />
            <button type="submit">Submit</button>
        </form>            
    </div>
)
```

**Comment by bn-s** [comment]
Hi @kasparpollet,

To quote from the [CSRF protection section](https://inertiajs.com/csrf-protection) in the Inertia docs, "a better approach is to use the CSRF functionality already built into Axios for this... simply include the XSRF-TOKEN cookie on each response"

So try adding `CSRF_COOKIE_NAME = 'XSRF-TOKEN'` to your `settings.py`.

Axios should then pick up the CSRF token from the cookie without you needing to do anything else. That also means you can drop the hidden CSRF field in your forms--Axios should now be taking care of all the manual work for you.

**Comment by kasparpollet** [comment]
Hi @bn-s 

Thanks for the reply and it works!
Something to mention: also add `CSRF_HEADER_NAME = 'HTTP_X_XSRF_TOKEN'` to the `settings.py` [Django docs](https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-header-name)

And the form data is not communicated via the `request.POST` but via `request.body`

**Comment by bn-s** [comment]
Good points.

Just a couple of notes about potential gotchas which are worth mentioning here:

#### 1) Inertia submits both `multipart/form-data` and `application/json` requests
Inertia submits forms as a `multipart/form-data` requests when uploading files (therefore the form data object will be received as is usually expected in typical Django... i.e. via `request.POST`).

However (and this is the gotcha), if a form contains a file upload field but no file is selected prior to form submission, Inertia will submit it as an `application/json` request (the behavior you describe above regarding `request.body`). This could cause problems unless you test for this behavior.

A simple way to do this would be something like this (however, given the vagueries of the internet, you're going to want to use a slightly more robust test, and also handle things like `JSONDecodeError` exceptions):

```python
if self.request.META.get('CONTENT_TYPE') == 'application/json':
    data = json.loads(self.request.body.decode('utf-8'))
else:
    data = self.request.POST
```

The nice thing about this test is that you could then create a form mixin allowing you to use regular Django forms with inertia like this:

```python
class InertiaFormMixin:
    def __init__(self, request=None, *args, **kwargs):
        data = None
        files = None
        if request:
            if request.META.get('CONTENT_TYPE') == 'application/json':
                data = json.loads(request.body.decode('utf-8'))
            else:
                data = request.POST
            files = request.FILES

        super().__init__(data, files, *args, **kwargs)
```

You would then create forms like so:

```python
class FooForm(InertiaFormMixin, forms.Form):
    bar_field = forms.BazField()
```

Then, to instantiate this from from your views you would just pass the request object in like so:
```python
form = FooForm(request)`
```

**Note:** I haven't tested any of the above suggestions: use at your own risk.

#### 2) Overriding Inertia's default behavior

Alternatively, you can also override Inertia's default `application/json` submissions and force it to make `multipart/form-data` requests like so:

```javascript
Inertia.post('/users', data, {
  forceFormData: true,
})
```
